version: "3.8"

services:
  vault:
    ports:
      - "5696:5696"
      - "8200:8200"
      - "8201:8201"
    image: "hashicorp/vault-enterprise:latest"
    cap_add:
      - IPC_LOCK
    environment:
      - 'VAULT_ADDR=http://127.0.0.1:8200'
      - 'VAULT_DEV_ROOT_TOKEN_ID=root'
      - 'VAULT_LICENSE_PATH=/opt/vault/lic/vault.hclic'
      - 'VAULT_SKIP_VERIFY=true'
    volumes:
      - type: bind
        source: ./vault.hcl
        target: /opt/vault/config/vault.hcl
      - type: bind
        source: /tmp/vault.hclic
        target: /opt/vault/lic/vault.hclic
    entrypoint: [ "sh", "-c", "vault server -config /opt/vault/config/vault.hcl -log-level=trace"] 
  vaultsetup:
    expose:
      - "8200"
    image: "ubuntu:22.04"
    depends_on:
      - vault
    # restart: "no"
    network_mode: "bridge"
    entrypoint: [ "sh", "-c", "/sensitive/helper.sh"] 
    volumes:
      - type: bind
        source: ./../terraform
        target: /terraform
      - type: bind
        source: ./../sensitive
        target: /sensitive
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
    ports:
      - 1521:1521
    volumes:
      - type: bind
        source: ./../oracle-backup
        target: /opt/oracle/backup
      - type: bind
        source: ./../oracle-data
        target: /opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
    network_mode: "bridge"

